//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.20 at 11:23:40 AM EDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="planet-name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="color">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *                 &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="eccentricity" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="eccentricityDelta" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="true-anamoly" use="required" type="{http://www.w3.org/2001/XMLSchema}double" fixed="0.0" />
 *       &lt;attribute name="ascending-node" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="ascending-nodeDelta" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="inclination" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="inclinationDelta" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mean-anamoly" use="required" type="{http://www.w3.org/2001/XMLSchema}double" fixed="0.0" />
 *       &lt;attribute name="rotational-period" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="radius" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="oblateness" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="obliquity" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="atmo" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="semi-major-axis" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="semi-major-axisDelta" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mass" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="arg-of-perhelion" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="arg-of-perhelionDelta" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="dm" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="period" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="epoch-longitude" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="epoch-longitudeDelta" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="perihelion-angle" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="mean-anamoly0" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *       &lt;attribute name="epochDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "planetName",
    "color"
})
@XmlRootElement(name = "planet", namespace = "orbitData")
public class Planet {

    @XmlElement(name = "planet-name", namespace = "orbitData", required = true)
    protected String planetName;
    @XmlElement(namespace = "orbitData", required = true)
    protected Planet.Color color;
    @XmlAttribute(name = "eccentricity", required = true)
    protected double eccentricity;
    @XmlAttribute(name = "eccentricityDelta", required = true)
    protected double eccentricityDelta;
    @XmlAttribute(name = "true-anamoly", required = true)
    protected double trueAnamoly;
    @XmlAttribute(name = "ascending-node", required = true)
    protected double ascendingNode;
    @XmlAttribute(name = "ascending-nodeDelta", required = true)
    protected double ascendingNodeDelta;
    @XmlAttribute(name = "inclination", required = true)
    protected double inclination;
    @XmlAttribute(name = "inclinationDelta", required = true)
    protected double inclinationDelta;
    @XmlAttribute(name = "mean-anamoly", required = true)
    protected double meanAnamoly;
    @XmlAttribute(name = "rotational-period", required = true)
    protected double rotationalPeriod;
    @XmlAttribute(name = "radius", required = true)
    protected double radius;
    @XmlAttribute(name = "oblateness", required = true)
    protected double oblateness;
    @XmlAttribute(name = "obliquity", required = true)
    protected double obliquity;
    @XmlAttribute(name = "atmo", required = true)
    protected boolean atmo;
    @XmlAttribute(name = "semi-major-axis", required = true)
    protected double semiMajorAxis;
    @XmlAttribute(name = "semi-major-axisDelta", required = true)
    protected double semiMajorAxisDelta;
    @XmlAttribute(name = "mass", required = true)
    protected double mass;
    @XmlAttribute(name = "arg-of-perhelion", required = true)
    protected double argOfPerhelion;
    @XmlAttribute(name = "arg-of-perhelionDelta", required = true)
    protected double argOfPerhelionDelta;
    @XmlAttribute(name = "dm", required = true)
    protected double dm;
    @XmlAttribute(name = "period", required = true)
    protected double period;
    @XmlAttribute(name = "epoch-longitude", required = true)
    protected double epochLongitude;
    @XmlAttribute(name = "epoch-longitudeDelta", required = true)
    protected double epochLongitudeDelta;
    @XmlAttribute(name = "perihelion-angle", required = true)
    protected double perihelionAngle;
    @XmlAttribute(name = "mean-anamoly0", required = true)
    protected double meanAnamoly0;
    @XmlAttribute(name = "epochDateTime")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar epochDateTime;

    /**
     * Gets the value of the planetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanetName() {
        return planetName;
    }

    /**
     * Sets the value of the planetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanetName(String value) {
        this.planetName = value;
    }

    /**
     * Gets the value of the color property.
     * 
     * @return
     *     possible object is
     *     {@link Planet.Color }
     *     
     */
    public Planet.Color getColor() {
        return color;
    }

    /**
     * Sets the value of the color property.
     * 
     * @param value
     *     allowed object is
     *     {@link Planet.Color }
     *     
     */
    public void setColor(Planet.Color value) {
        this.color = value;
    }

    /**
     * Gets the value of the eccentricity property.
     * 
     */
    public double getEccentricity() {
        return eccentricity;
    }

    /**
     * Sets the value of the eccentricity property.
     * 
     */
    public void setEccentricity(double value) {
        this.eccentricity = value;
    }

    /**
     * Gets the value of the eccentricityDelta property.
     * 
     */
    public double getEccentricityDelta() {
        return eccentricityDelta;
    }

    /**
     * Sets the value of the eccentricityDelta property.
     * 
     */
    public void setEccentricityDelta(double value) {
        this.eccentricityDelta = value;
    }

    /**
     * Gets the value of the trueAnamoly property.
     * 
     */
    public double getTrueAnamoly() {
        return trueAnamoly;
    }

    /**
     * Sets the value of the trueAnamoly property.
     * 
     */
    public void setTrueAnamoly(double value) {
        this.trueAnamoly = value;
    }

    /**
     * Gets the value of the ascendingNode property.
     * 
     */
    public double getAscendingNode() {
        return ascendingNode;
    }

    /**
     * Sets the value of the ascendingNode property.
     * 
     */
    public void setAscendingNode(double value) {
        this.ascendingNode = value;
    }

    /**
     * Gets the value of the ascendingNodeDelta property.
     * 
     */
    public double getAscendingNodeDelta() {
        return ascendingNodeDelta;
    }

    /**
     * Sets the value of the ascendingNodeDelta property.
     * 
     */
    public void setAscendingNodeDelta(double value) {
        this.ascendingNodeDelta = value;
    }

    /**
     * Gets the value of the inclination property.
     * 
     */
    public double getInclination() {
        return inclination;
    }

    /**
     * Sets the value of the inclination property.
     * 
     */
    public void setInclination(double value) {
        this.inclination = value;
    }

    /**
     * Gets the value of the inclinationDelta property.
     * 
     */
    public double getInclinationDelta() {
        return inclinationDelta;
    }

    /**
     * Sets the value of the inclinationDelta property.
     * 
     */
    public void setInclinationDelta(double value) {
        this.inclinationDelta = value;
    }

    /**
     * Gets the value of the meanAnamoly property.
     * 
     */
    public double getMeanAnamoly() {
        return meanAnamoly;
    }

    /**
     * Sets the value of the meanAnamoly property.
     * 
     */
    public void setMeanAnamoly(double value) {
        this.meanAnamoly = value;
    }

    /**
     * Gets the value of the rotationalPeriod property.
     * 
     */
    public double getRotationalPeriod() {
        return rotationalPeriod;
    }

    /**
     * Sets the value of the rotationalPeriod property.
     * 
     */
    public void setRotationalPeriod(double value) {
        this.rotationalPeriod = value;
    }

    /**
     * Gets the value of the radius property.
     * 
     */
    public double getRadius() {
        return radius;
    }

    /**
     * Sets the value of the radius property.
     * 
     */
    public void setRadius(double value) {
        this.radius = value;
    }

    /**
     * Gets the value of the oblateness property.
     * 
     */
    public double getOblateness() {
        return oblateness;
    }

    /**
     * Sets the value of the oblateness property.
     * 
     */
    public void setOblateness(double value) {
        this.oblateness = value;
    }

    /**
     * Gets the value of the obliquity property.
     * 
     */
    public double getObliquity() {
        return obliquity;
    }

    /**
     * Sets the value of the obliquity property.
     * 
     */
    public void setObliquity(double value) {
        this.obliquity = value;
    }

    /**
     * Gets the value of the atmo property.
     * 
     */
    public boolean isAtmo() {
        return atmo;
    }

    /**
     * Sets the value of the atmo property.
     * 
     */
    public void setAtmo(boolean value) {
        this.atmo = value;
    }

    /**
     * Gets the value of the semiMajorAxis property.
     * 
     */
    public double getSemiMajorAxis() {
        return semiMajorAxis;
    }

    /**
     * Sets the value of the semiMajorAxis property.
     * 
     */
    public void setSemiMajorAxis(double value) {
        this.semiMajorAxis = value;
    }

    /**
     * Gets the value of the semiMajorAxisDelta property.
     * 
     */
    public double getSemiMajorAxisDelta() {
        return semiMajorAxisDelta;
    }

    /**
     * Sets the value of the semiMajorAxisDelta property.
     * 
     */
    public void setSemiMajorAxisDelta(double value) {
        this.semiMajorAxisDelta = value;
    }

    /**
     * Gets the value of the mass property.
     * 
     */
    public double getMass() {
        return mass;
    }

    /**
     * Sets the value of the mass property.
     * 
     */
    public void setMass(double value) {
        this.mass = value;
    }

    /**
     * Gets the value of the argOfPerhelion property.
     * 
     */
    public double getArgOfPerhelion() {
        return argOfPerhelion;
    }

    /**
     * Sets the value of the argOfPerhelion property.
     * 
     */
    public void setArgOfPerhelion(double value) {
        this.argOfPerhelion = value;
    }

    /**
     * Gets the value of the argOfPerhelionDelta property.
     * 
     */
    public double getArgOfPerhelionDelta() {
        return argOfPerhelionDelta;
    }

    /**
     * Sets the value of the argOfPerhelionDelta property.
     * 
     */
    public void setArgOfPerhelionDelta(double value) {
        this.argOfPerhelionDelta = value;
    }

    /**
     * Gets the value of the dm property.
     * 
     */
    public double getDm() {
        return dm;
    }

    /**
     * Sets the value of the dm property.
     * 
     */
    public void setDm(double value) {
        this.dm = value;
    }

    /**
     * Gets the value of the period property.
     * 
     */
    public double getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     */
    public void setPeriod(double value) {
        this.period = value;
    }

    /**
     * Gets the value of the epochLongitude property.
     * 
     */
    public double getEpochLongitude() {
        return epochLongitude;
    }

    /**
     * Sets the value of the epochLongitude property.
     * 
     */
    public void setEpochLongitude(double value) {
        this.epochLongitude = value;
    }

    /**
     * Gets the value of the epochLongitudeDelta property.
     * 
     */
    public double getEpochLongitudeDelta() {
        return epochLongitudeDelta;
    }

    /**
     * Sets the value of the epochLongitudeDelta property.
     * 
     */
    public void setEpochLongitudeDelta(double value) {
        this.epochLongitudeDelta = value;
    }

    /**
     * Gets the value of the perihelionAngle property.
     * 
     */
    public double getPerihelionAngle() {
        return perihelionAngle;
    }

    /**
     * Sets the value of the perihelionAngle property.
     * 
     */
    public void setPerihelionAngle(double value) {
        this.perihelionAngle = value;
    }

    /**
     * Gets the value of the meanAnamoly0 property.
     * 
     */
    public double getMeanAnamoly0() {
        return meanAnamoly0;
    }

    /**
     * Sets the value of the meanAnamoly0 property.
     * 
     */
    public void setMeanAnamoly0(double value) {
        this.meanAnamoly0 = value;
    }

    /**
     * Gets the value of the epochDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEpochDateTime() {
        return epochDateTime;
    }

    /**
     * Sets the value of the epochDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEpochDateTime(XMLGregorianCalendar value) {
        this.epochDateTime = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="red" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="green" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *       &lt;attribute name="blue" type="{http://www.w3.org/2001/XMLSchema}int" default="0" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Color {

        @XmlAttribute(name = "red")
        protected Integer red;
        @XmlAttribute(name = "green")
        protected Integer green;
        @XmlAttribute(name = "blue")
        protected Integer blue;

        /**
         * Gets the value of the red property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getRed() {
            if (red == null) {
                return  0;
            } else {
                return red;
            }
        }

        /**
         * Sets the value of the red property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRed(Integer value) {
            this.red = value;
        }

        /**
         * Gets the value of the green property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getGreen() {
            if (green == null) {
                return  0;
            } else {
                return green;
            }
        }

        /**
         * Sets the value of the green property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setGreen(Integer value) {
            this.green = value;
        }

        /**
         * Gets the value of the blue property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getBlue() {
            if (blue == null) {
                return  0;
            } else {
                return blue;
            }
        }

        /**
         * Sets the value of the blue property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setBlue(Integer value) {
            this.blue = value;
        }

    }

}
