//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.20 at 11:23:40 AM EDT 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="refName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="rPer" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="vPer" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rAph" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="vAph" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ecc" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="a" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="refX" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="refY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="refZ" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rocketX" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rocketY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="rocketZ" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="moonX" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="moonY" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="moonZ" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "refName",
    "rPer",
    "vPer",
    "rAph",
    "vAph",
    "ecc",
    "a",
    "refX",
    "refY",
    "refZ",
    "rocketX",
    "rocketY",
    "rocketZ",
    "moonX",
    "moonY",
    "moonZ"
})
@XmlRootElement(name = "RocketDataResponse", namespace = "dave")
public class RocketDataResponse {

    @XmlElement(namespace = "dave", required = true)
    protected String refName;
    @XmlElement(namespace = "dave")
    protected double rPer;
    @XmlElement(namespace = "dave")
    protected double vPer;
    @XmlElement(namespace = "dave")
    protected double rAph;
    @XmlElement(namespace = "dave")
    protected double vAph;
    @XmlElement(namespace = "dave")
    protected double ecc;
    @XmlElement(namespace = "dave")
    protected double a;
    @XmlElement(namespace = "dave")
    protected double refX;
    @XmlElement(namespace = "dave")
    protected double refY;
    @XmlElement(namespace = "dave")
    protected double refZ;
    @XmlElement(namespace = "dave")
    protected double rocketX;
    @XmlElement(namespace = "dave")
    protected double rocketY;
    @XmlElement(namespace = "dave")
    protected double rocketZ;
    @XmlElement(namespace = "dave")
    protected double moonX;
    @XmlElement(namespace = "dave")
    protected double moonY;
    @XmlElement(namespace = "dave")
    protected double moonZ;

    /**
     * Gets the value of the refName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefName() {
        return refName;
    }

    /**
     * Sets the value of the refName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefName(String value) {
        this.refName = value;
    }

    /**
     * Gets the value of the rPer property.
     * 
     */
    public double getRPer() {
        return rPer;
    }

    /**
     * Sets the value of the rPer property.
     * 
     */
    public void setRPer(double value) {
        this.rPer = value;
    }

    /**
     * Gets the value of the vPer property.
     * 
     */
    public double getVPer() {
        return vPer;
    }

    /**
     * Sets the value of the vPer property.
     * 
     */
    public void setVPer(double value) {
        this.vPer = value;
    }

    /**
     * Gets the value of the rAph property.
     * 
     */
    public double getRAph() {
        return rAph;
    }

    /**
     * Sets the value of the rAph property.
     * 
     */
    public void setRAph(double value) {
        this.rAph = value;
    }

    /**
     * Gets the value of the vAph property.
     * 
     */
    public double getVAph() {
        return vAph;
    }

    /**
     * Sets the value of the vAph property.
     * 
     */
    public void setVAph(double value) {
        this.vAph = value;
    }

    /**
     * Gets the value of the ecc property.
     * 
     */
    public double getEcc() {
        return ecc;
    }

    /**
     * Sets the value of the ecc property.
     * 
     */
    public void setEcc(double value) {
        this.ecc = value;
    }

    /**
     * Gets the value of the a property.
     * 
     */
    public double getA() {
        return a;
    }

    /**
     * Sets the value of the a property.
     * 
     */
    public void setA(double value) {
        this.a = value;
    }

    /**
     * Gets the value of the refX property.
     * 
     */
    public double getRefX() {
        return refX;
    }

    /**
     * Sets the value of the refX property.
     * 
     */
    public void setRefX(double value) {
        this.refX = value;
    }

    /**
     * Gets the value of the refY property.
     * 
     */
    public double getRefY() {
        return refY;
    }

    /**
     * Sets the value of the refY property.
     * 
     */
    public void setRefY(double value) {
        this.refY = value;
    }

    /**
     * Gets the value of the refZ property.
     * 
     */
    public double getRefZ() {
        return refZ;
    }

    /**
     * Sets the value of the refZ property.
     * 
     */
    public void setRefZ(double value) {
        this.refZ = value;
    }

    /**
     * Gets the value of the rocketX property.
     * 
     */
    public double getRocketX() {
        return rocketX;
    }

    /**
     * Sets the value of the rocketX property.
     * 
     */
    public void setRocketX(double value) {
        this.rocketX = value;
    }

    /**
     * Gets the value of the rocketY property.
     * 
     */
    public double getRocketY() {
        return rocketY;
    }

    /**
     * Sets the value of the rocketY property.
     * 
     */
    public void setRocketY(double value) {
        this.rocketY = value;
    }

    /**
     * Gets the value of the rocketZ property.
     * 
     */
    public double getRocketZ() {
        return rocketZ;
    }

    /**
     * Sets the value of the rocketZ property.
     * 
     */
    public void setRocketZ(double value) {
        this.rocketZ = value;
    }

    /**
     * Gets the value of the moonX property.
     * 
     */
    public double getMoonX() {
        return moonX;
    }

    /**
     * Sets the value of the moonX property.
     * 
     */
    public void setMoonX(double value) {
        this.moonX = value;
    }

    /**
     * Gets the value of the moonY property.
     * 
     */
    public double getMoonY() {
        return moonY;
    }

    /**
     * Sets the value of the moonY property.
     * 
     */
    public void setMoonY(double value) {
        this.moonY = value;
    }

    /**
     * Gets the value of the moonZ property.
     * 
     */
    public double getMoonZ() {
        return moonZ;
    }

    /**
     * Sets the value of the moonZ property.
     * 
     */
    public void setMoonZ(double value) {
        this.moonZ = value;
    }

}
